const words = [
    // 3-letter words
    "ace", "ant", "art", "bag", "bat", "bay", "bee", "bin", "bow", "bus",
    "cat", "cop", "cow", "cub", "cup", "dam", "dew", "dog", "dot", "dry",
    "ear", "eel", "egg", "elf", "elk", "eye", "fan", "fig", "fix", "fox",
    "fun", "gap", "gem", "gum", "gut", "hat", "hay", "hen", "hip", "hog",
    "ice", "ink", "ivy", "jam", "jaw", "jet", "job", "jog", "jug", "key",
    "kit", "lab", "lap", "law", "leg", "log", "mad", "map", "mop", "mud",
    "net", "nut", "oak", "owl", "pad", "pal", "pan", "pen", "pet", "pit",
    "pot", "rag", "rat", "red", "rib", "rod", "rug", "run", "sap", "set",
    "sip", "sit", "sun", "tap", "tar", "tea", "tip", "toe", "top", "toy",
    "urn", "van", "vet", "web", "wig", "win", "yak", "yap", "yes", "zap",
    
    // 4-letter words
    "able", "arch", "bake", "bead", "bell", "belt", "bend", "bore", "card", "clap",
    "clay", "clue", "coal", "cope", "cove", "cure", "dart", "dawn", "deed", "deer",
    "dive", "door", "dust", "echo", "epic", "face", "fact", "fame", "fate", "fear",
    "fire", "flap", "flee", "flood", "flow", "food", "foot", "game", "glow", "goat",
    "gold", "good", "grim", "grip", "grow", "hate", "have", "hero", "hope", "idea",
    "iron", "jump", "kite", "lamp", "lake", "leaf", "life", "lion", "love", "luck",
    "maze", "mint", "moon", "name", "nest", "oath", "opal", "page", "pale", "path",
    "peel", "pond", "quiz", "rain", "ring", "road", "roof", "rose", "rule", "sail",
    "seed", "shut", "sing", "skip", "snow", "soar", "soap", "star", "stay", "stone",
    "swim", "take", "test", "time", "tree", "trip", "true", "unit", "vase", "walk",
    "wind", "wish", "wolf", "work", "worm", "yard", "yawn", "zone",

    // 5-letter words
    "apple", "badge", "brave", "candy", "cease", "charm", "cloud", "coast", "crisp", "dance",
    "delta", "demon", "doubt", "draft", "dream", "drink", "eagle", "earth", "elite", "error",
    "fable", "fancy", "feast", "flash", "float", "flood", "flute", "force", "frost", "ghost",
    "giant", "glove", "grape", "great", "green", "grind", "group", "happy", "haste", "heart",
    "honor", "horse", "house", "human", "ideal", "image", "jolly", "joker", "jumpy", "karma",
    "latch", "lucky", "magic", "mango", "marry", "melon", "metal", "minor", "model", "music",
    "noble", "novel", "oasis", "ocean", "orbit", "paint", "pearl", "pilot", "piano", "place",
    "plain", "plume", "power", "pride", "quick", "quiet", "quirk", "raven", "rider", "risky",
    "river", "robot", "royal", "savage", "scout", "sense", "shade", "sheep", "shift", "shock",
    "silent", "smart", "smile", "snake", "solar", "solid", "spend", "spice", "spike", "spine",
    "storm", "sugar", "sunny", "swift", "table", "tiger", "title", "toxic", "track", "trail",
    "tribe", "trust", "twist", "ultra", "urban", "vigor", "visit", "vivid", "wagon", "witty",
    "whale", "windy", "world", "wrist", "xerox", "young", "zebra", "zephyr", "zesty",

    // 6-letter words
    "anchor", "beacon", "beauty", "breeze", "bronze", "castle", "charge", "chimney", "circle",
    "coffin", "collar", "comedy", "daring", "danger", "dazzle", "dragon", "eclipse", "empire",
    "enrich", "escape", "excite", "expert", "forest", "frozen", "gadget", "galaxy", "genius",
    "glance", "glider", "goblet", "gospel", "grande", "guitar", "harbor", "helium", "horizon",
    "icebox", "impact", "insane", "jaguar", "jungle", "kitten", "lagoon", "lawyer", "legend",
    "loyalty", "mammal", "meteor", "mirror", "modern", "moment", "museum", "nature", "nebula",
    "notion", "novice", "oyster", "palace", "parcel", "pastel", "pirate", "planet", "plasma",
    "plunge", "pocket", "portal", "prince", "profit", "puzzle", "quartz", "replay", "rescue",
    "rocket", "safari", "safety", "shadow", "silent", "slogan", "spirit", "stable", "strain",
    "stream", "summit", "temple", "theory", "tunnel", "turkey", "unique", "united", "unseen",
    "update", "utopia", "valley", "velvet", "voyage", "wallet", "wander", "wizard", "wonder",
    "worthy", "xylophone", "yonder", "zephyr"
];
